import React from 'react';
import { C } from '../../styles/theme';
import { Card, Btn } from '../../components/CommonUI';

export default function TermsOfService({ onBack }) {
  return (
    <div style={{ animation: 'fadeIn 0.5s ease' }}>
      <Btn onClick={onBack} color={C.muted} style={{ marginBottom: 24 }}>← Back to Platform</Btn>
      
      <Card style={{ padding: 40, lineHeight: 1.6 }}>
        <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 32, marginBottom: 24, color: C.text }}>Terms of Service</h1>
        <p style={{ color: C.muted, fontSize: 13, marginBottom: 32 }}>Last Updated: March 2026</p>

        <section style={{ marginBottom: 32 }}>
          <h2 style={{ fontSize: 18, color: C.accent, marginBottom: 12 }}>1. Acceptance of Terms</h2>
          <p style={{ color: C.text }}>
            By accessing CareerAiHub, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform.
          </p>
        </section>

        <section style={{ marginBottom: 32 }}>
          <h2 style={{ fontSize: 18, color: C.accent, marginBottom: 12 }}>2. Use of AI Tools</h2>
          <p style={{ color: C.text }}>
            Our platform provides AI-generated suggestions for resumes, applications, and interview preparation. While we strive for high accuracy, the results are generated by Large Language Models and should be reviewed by you before use in professional settings.
          </p>
        </section>

        <section style={{ marginBottom: 32 }}>
          <h2 style={{ fontSize: 18, color: C.accent, marginBottom: 12 }}>3. User Conduct</h2>
          <p style={{ color: C.text }}>
            Users are responsible for the accuracy of the information they provide. You may not use the platform to generate misleading or fraudulent career documents.
          </p>
        </section>

        <section style={{ marginBottom: 32 }}>
          <h2 style={{ fontSize: 18, color: C.accent, marginBottom: 12 }}>4. Limitation of Liability</h2>
          <p style={{ color: C.text }}>
            CareerAiHub provides tools for career advancement but does not guarantee employment or specific outcomes. We are not liable for any professional decisions made based on AI-generated suggestions.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: 18, color: C.accent, marginBottom: 12 }}>5. Modifications</h2>
          <p style={{ color: C.text }}>
            We reserve the right to modify these terms as our platform evolves. Continued use after changes constitutes acceptance of the new terms.
          </p>
        </section>
      </Card>
    </div>
  );
}
